<a href="https://colab.research.google.com/github/Dean12343/MAT494/blob/main/MAT494_1_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Problem 1: Find U, Sigma, and V^T for the Singular Value Decomposition of the following matrix and verify that A=(U)(Sigma)(V^T):


---

 \begin{bmatrix}
7 & 5 &10&5 \\
2 & 1 & 10&0\\
8 & 4 &5&10\\
0&6&2&1\\
1&5&0&2\\
\end{bmatrix}

In [ ]:
from numpy.core.shape_base import vstack
import numpy as np
a=np.array([[7,5,10,5], [2,1,10,0],[8,4,5,10],[0,6,2,1],[1,5,0,2]])
u, s, vT =  np.linalg.svd(a, full_matrices=False)
s=np.diag(s)
print( "U=\n", u, "\nS=\n", s, "\nV^T=\n",vT)
b=np.dot(s,vT)
print("A=\n",np.dot(u,b))

U=
 [[-0.65401528 -0.19155502  0.02966276  0.7075142 ]
 [-0.36116648 -0.75428716  0.01525141 -0.46156692]
 [-0.61919317  0.53746246 -0.39687793 -0.41248791]
 [-0.18641234  0.09082321  0.75643159 -0.31841998]
 [-0.15386043  0.31183778  0.51883203  0.12182806]] 
S=
 [[21.37525811  0.          0.          0.        ]
 [ 0.          8.9060661   0.          0.        ]
 [ 0.          0.          6.52258168  0.        ]
 [ 0.          0.          0.          1.11187021]] 
V^T=
 [[-0.48691088 -0.37406761 -0.63721374 -0.46577877]
 [ 0.19785144  0.28541398 -0.73988481  0.57616328]
 [-0.37071966  0.87523675 -0.00343189 -0.3106699 ]
 [ 0.76572811  0.11212898 -0.21567877 -0.59545799]]
A=
 [[ 7.00000000e+00  5.00000000e+00  1.00000000e+01  5.00000000e+00]
 [ 2.00000000e+00  1.00000000e+00  1.00000000e+01 -4.41998272e-15]
 [ 8.00000000e+00  4.00000000e+00  5.00000000e+00  1.00000000e+01]
 [ 8.59238477e-16  6.00000000e+00  2.00000000e+00  1.00000000e+00]
 [ 1.00000000e+00  5.00000000e+00  7.04022714e

Problem 2: Lower the Rank of the matrix from problem 1 to ranks 1 and 3, and find the new matrix for each respective rank



---

 \begin{bmatrix}
7 & 5 &10&5 \\
2 & 1 & 10&0\\
8 & 4 &5&10\\
0&6&2&1\\
1&5&0&2\\
\end{bmatrix}



In [ ]:
from numpy.core.shape_base import vstack
a=np.array([[7,5,10,5], [2,1,10,0],[8,4,5,10],[0,6,2,1],[1,5,0,2]])
u, s, vT =  np.linalg.svd(a, full_matrices=False)
s=np.diag(s)
for r in (1,3):
  n=u[:, :r]@s[0:r,:r]@vT[:r,:]
  print("rank", r, "matrix:\n",n)

rank 1 matrix:
 [[6.80689021 5.22937006 8.90808595 6.51146862]
 [3.75896506 2.88781201 4.91930717 3.59582456]
 [6.44446704 4.9509397  8.43378762 6.16477475]
 [1.94015091 1.49051428 2.53904949 1.85594763]
 [1.60135567 1.230236   2.09567269 1.53185623]]
rank 3 matrix:
 [[ 6.39762929  4.91179218 10.16966672  5.46842534]
 [ 2.39297359  1.05754487  9.88931311 -0.30559054]
 [ 8.3511882   4.05142605  4.90108259  9.7269033 ]
 [ 0.27109967  6.03969833  1.92364072  0.78918305]
 [ 0.89627677  4.98481135  0.0292152   2.08065895]]


Problem 3: Find the covariance matrix and total variance:


---

 \begin{bmatrix}
7 & 5 &10&5 \\
2 & 1 & 10&0\\
8 & 4 &5&10\\
0&6&2&1\\
1&5&0&2\\
\end{bmatrix}

In [ ]:
a=np.array([[7,5,10,5], [2,1,10,0],[8,4,5,10],[0,6,2,1],[1,5,0,2]])
M=1/4*(a[:,[0]]+a[:,[1]]+a[:,[2]]+a[:,[3]])
b=np.array([[],[],[],[],[]])
for r in (0,1,2,3):
  x=a[:,[r]]-M
  b=np.column_stack((b,x))
s=1/3*(np.dot(b,b.T))
print("Covariance Matrix:\n",s)
print("Total Variance:\n",np.trace(s))

Covariance Matrix:
 [[ 5.58333333 10.41666667 -2.08333333 -1.91666667 -4.        ]
 [10.41666667 20.91666667 -5.91666667 -1.08333333 -6.33333333]
 [-2.08333333 -5.91666667  7.58333333 -5.58333333 -2.        ]
 [-1.91666667 -1.08333333 -5.58333333  6.91666667  4.66666667]
 [-4.         -6.33333333 -2.          4.66666667  4.66666667]]
Total Variance:
 45.66666666666666
