Problem 1: Display the matrix A and its transpose given that A is the following:

---
 \begin{bmatrix}
1 & 2\\
3 & 4\\
5 & 6
\end{bmatrix}

In [72]:
import numpy as np

A = np.array([[1, 2], [3, 4], [5, 6]])
print("A = ",A)
print("Aᵀ= ", A.T)

A =  [[1 2]
 [3 4]
 [5 6]]
Aᵀ=  [[1 3 5]
 [2 4 6]]


Problem 2: Form a 5x5 Identity Matrix

In [5]:
A=np.eye(5)
print(A)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


Problem 3: Find the RREF of the following matrix

---
 \begin{bmatrix}
1 & 2 & 3\\
2 & 4 & 6\\
6 & 7 & 8
\end{bmatrix}

In [73]:
from sympy import * 
a=Matrix([[1,2,3], [2,4,6],[6,7,8]])
b=a.rref()
print(np.array(b[0]))

[[1 0 -1]
 [0 1 2]
 [0 0 0]]


Problem 4: Find the coefficients for a linear combination of vectors such that $a\overrightarrow{v_1}$+$b\overrightarrow{v_2}$+$c\overrightarrow{v_3}$=$\overrightarrow{w}$ with basis vectors $\overrightarrow{v_1}=<1,4,3>$, $\overrightarrow{v_2}=<4,5,6>$, and $\overrightarrow{v_3}=<7,8,9>$ that form the vector $\overrightarrow{w}=<2,4,6>$ 

In [71]:
a=np.array([[1,4,7,2], [4,5,8,4],[3,6,9,6]])
b=sympy.Matrix(a).rref()
c=np.array(b[0])
print("a = ",c[0,-1])
print("b = ",c[1,-1])
print("c = ",c[2,-1])

a =  0
b =  4
c =  -2


Problem 5: Show that det(A)=det(Aᵀ) where A is the following:

---
 \begin{bmatrix}

> Indented block


6 & 1 & 8\\
7 & 4 & 10\\
8 & 8 & 4
\end{bmatrix}



In [48]:
a=np.array([[6,1,8],[7,4,10],[8,8,4]])
a1=np.linalg.det(a)
x1=round(a1,0)
a2=np.linalg.det(a.T)
x2=round(a2,0)
print("Determinant of A=",x1)
print("Determinant of Aᵀ=",x2)

Determinant of A= -140.0
Determinant of Aᵀ= -140.0


Problem 6: Use the Gram-Schmidt Process to find Orthonormal Basis vectors for the space spanned by the following: {<2,0,8>, <8,7,7>, <9,4,0>}.

In [105]:
a = [Matrix([2,0,8]), Matrix([8,7,7]), Matrix([9,4,0])]
b = GramSchmidt(a, True)
x1=np.array(b[0])
x2=np.array(b[1])
x3=np.array(b[2])
print("v1 = ", x1)
print("v2 = ", x2)
print("v3 = ", x3)

v1 =  [[sqrt(17)/17]
 [0]
 [4*sqrt(17)/17]]
v2 =  [[50*sqrt(34)/459]
 [7*sqrt(34)/54]
 [-25*sqrt(34)/918]]
v3 =  [[14*sqrt(2)/27]
 [-25*sqrt(2)/54]
 [-7*sqrt(2)/54]]


Problem 7: Show that the basis vectors from problem 6 are orthogonal and have a norm of 1

In [86]:
a = [Matrix([2,0,8]), Matrix([8,7,7]), Matrix([9,4,0])]
b = GramSchmidt(a, True)
x1=np.array(b[0])
x2=np.array(b[1])
x3=np.array(b[2])
y1=x1.T.dot(x2)
y2=x1.T.dot(x3)
y3=x2.T.dot(x3)
z1=x1.T.dot(x1)
z2=x2.T.dot(x2)
z3=x3.T.dot(x3)
print("x1 and x2 are orthogonal",y1==0)
print("x1 and x3 are orthogonal",y2==0)
print("x2 and x3 are orthogonal",y3==0)
print("x1 is normalized", z1==1)
print("x2 is normalized", z2==1)
print("x3 is normalized", z3==1)

x1 and x2 are orthogonal [[ True]]
x1 and x3 are orthogonal [[ True]]
x2 and x3 are orthogonal [[ True]]
x1 is normalized [[ True]]
x2 is normalized [[ True]]
x3 is normalized [[ True]]


Problem 8: Find the Eigenvalues and Eigenvectors of the Following Matrix:

---

\begin{bmatrix}
1 & 3\\
5 & 4\\
\end{bmatrix}

In [101]:
a=Matrix([[1,3],[5,4]])
b=a.eigenvals()
c=a.eigenvects()
print("The eigenvalues are:",b)
print("The eigenvectors are:",c)

The eigenvalues are: {5/2 - sqrt(69)/2: 1, 5/2 + sqrt(69)/2: 1}
The eigenvectors are: [(5/2 - sqrt(69)/2, 1, [Matrix([
[-3/(-3/2 + sqrt(69)/2)],
[                     1]])]), (5/2 + sqrt(69)/2, 1, [Matrix([
[-3/(-sqrt(69)/2 - 3/2)],
[                     1]])])]


Problem 9: Diagonalize A by finding P and D such that $PDP^{-1}=A$ where A is the following:


---

 \begin{bmatrix}
1 & 3\\
5 & 4\\
\end{bmatrix}

In [102]:
a=Matrix([[1,3],[5,4]])
(p,d)=a.diagonalize()
print("P = ",p)
print("D = ",d)

P =  Matrix([[-sqrt(69)/10 - 3/10, -3/10 + sqrt(69)/10], [1, 1]])
D =  Matrix([[5/2 - sqrt(69)/2, 0], [0, 5/2 + sqrt(69)/2]])
