Problem 1: Find the QR Decomposition of the following matrix A and show that A=QR:


---
 \begin{bmatrix}
7 & 5 \\
2 & 1 \\
8 & 4 
\end{bmatrix}


In [77]:
import numpy as np
a=np.array([[7,5], [2,1],[8,4]])
q, r =  np.linalg.qr(a)
print( "Q=\n", q, "\nR=\n", r)
print("A=\n",np.dot(q,r))

Q=
 [[-0.64715023  0.7623625 ]
 [-0.18490007 -0.15695699]
 [-0.73960026 -0.62782794]] 
R=
 [[-10.81665383  -6.37905226]
 [  0.           1.14354375]]
A=
 [[7. 5.]
 [2. 1.]
 [8. 4.]]


Problem 2: Find the least-squares solution $\overrightarrow{x}$of the following matrix A and vector $\overrightarrow{b}$:

---

 \begin{bmatrix}
7 & 5 \\
2 & 1 \\
8 & 4 
\end{bmatrix}

 \begin{bmatrix}
2\\
2\\
1
\end{bmatrix}


In [73]:
a=np.array([[7.,5.], [2.,1.],[8.,4.],])
b=np.array([[2],[2],[1]])
c=np.dot(a.T,b)
d=np.dot(a.T,a)
x=np.dot(np.linalg.inv(d),c)
print("x=\n",x)

x=
 [[-0.07843137]
 [ 0.50980392]]


Problem 3: Find the error in the least-squares solution from problem 2

In [89]:
a=np.array([[7.,5.], [2.,1.],[8.,4.]])
b1=np.array([2,2,1])
b=np.array([[2],[2],[1]])
c=np.dot(a.T,b)
d=np.dot(a.T,a)
x=np.dot(np.linalg.inv(d),c)
e=np.dot(a,x)
n=np.linalg.norm(b-e)
print("error is\n", n)

error is
 1.697749375254331


Problem 4: Show that $Rx^*=Q^T\overrightarrow{b}$ where W is the space spanned by col(A) from problems 1 and 2

```



In [97]:
a=np.array([[7.,5.], [2.,1.],[8.,4.]])
q, r =  np.linalg.qr(a)
b=np.array([[2],[2],[1]])
c=np.dot(a.T,b)
d=np.dot(a.T,a)
x=np.dot(np.linalg.inv(d),c)
f=np.dot(r,x)
g=np.dot(q.T,b)
print("Rx*=\n",f)
print("QT*b=\n",g)

Rx*=
 [[-2.40370085]
 [ 0.58298309]]
QT*b=
 [[-2.40370085]
 [ 0.58298309]]
